accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('<int:user_pk>/password/', views.change_password, name='change_password')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django import forms


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label='사용자 이름',
        widget=forms.TextInput(
            attrs={
            'class': 'my-title',
            'placeholder': 'Enter the title',
            'maxlength': 10,
            }
         )
    )
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')



class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name', 'username', 'password')

movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm, CustomUserCreationForm


def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)  # 회원가입 후 로그인까지 이어서 진행
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    return redirect('movies:index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)  
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/change_password.html', context)

movies/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Movie
from .forms import MovieForm


def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)
    

@login_required
def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')


@login_required
def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movies/update.html', context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
  <h1>Password Change</h1>
  <form action="{% url "change_password" user.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

  <h1>Login Page</h1>
  <form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인">
  </form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>SIGNUP PAGE</h1>
  <form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>UPDATE PAGE</h1>
    <form action="{% url "accounts:update" %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="수정">
    </form>

    <br>

    <form action="{% url "accounts:delete" %}", method="POST">
        {% csrf_token %}
        <input type="submit" value="회원 탈퇴">
    </form>

    <form action="{% url "change_password" user.pk%}", method="POST">
        {% csrf_token %}
        <input type="submit" value="비밀번호 변경">
    </form>

{% endblock %}

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <form action="{% url "movies:create" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
{% endblock %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="detail_container">
        <h1>DETAIL PAGE</h1>

        <p class="detail_movie_title">{{ movie.title }}</p>
        <p>{{ movie.description }}</p>
    
        <hr>
    
        <div class="btn_container">
            <a href="{% url "movies:update" movie.pk %}" class="update_btn">UPDATE</a>
            <form action="{% url "movies:delete" movie.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="DELETE" class="delete_btn">
            </form>
        </div>
    
        <br>
        <a href="{% url "movies:index" %}" class="back_btn">BACK</a>
    </div>

{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1 class="index_title">INDEX PAGE</h1>

{% for movie in movies %}
    <div class="movie_container">
        <div class="movie_title">{{ movie.title }}</div>
        <div class="movie_description">{{ movie.description }}</div>
        <a href="{% url "movies:detail" movie.pk %}" class="detail_btn">Detail</a>
    </div>
{% endfor %}
{% endblock %}

movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update</h1>
    <form action="{% url "movies:update" movie.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
<style>

</style>

<body>
    {% if request.user.is_authenticated %}
        <nav class="nav">
            <div class="menu_container">
                <div class="logo">SSAFY</div>
                <a href="{% url "movies:index" %}" class="index">INDEX</a>
                <a href="{% url "movies:create" %}" class="create">CREATE</a>
                <a href="{% url "accounts:update" %}" class="user_update">회원 정보 수정</a>
                <a href="{% url 'change_password' user.pk%}" class="change_pwd">비밀번호 변경</a>
                <form action="{% url "accounts:logout" %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="로그아웃" class="logout">
                </form>
            </div>
        </nav>

    {% else %}
        <nav class="nav">
            <div class="menu_container_notlogin">
                <div class="logo">SSAFY</div>
                <a href="{% url "movies:index" %}" class="index">INDEX</a>
                <a href="{% url "accounts:signup" %}" class="signup">회원 가입</a>
                <form action="{% url "accounts:login" %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="로그인" class="login">
                </form>
            </div>
        </nav>

    {% endif %}


    {% block content %}
    {% endblock content %}
</body>
</html>